import ItgAtomVideo from './components/atoms/ItgAtomVideo'
import ItgCarouselImageCard from './components/blocks/ItgCarouselImageCard'
import ItgCarouselNumbers from './components/blocks/ItgCarouselNumbers'
import ItgAccordion from './components/atoms/ItgAccordion'
import ItgTabYears from './components/blocks/ItgTabYears'
import ItgMetaballs from './components/animations/ItgMetaballs'
//import ItgHamburgers from './components/animations/ItgHamburgers'
import ItgCarouselLaunches from './components/blocks/ItgCarouselLaunches'
<<<<<<< HEAD
import ItgHeroImageSwiper from './components/blocks/ItgHeroImageSlider'
=======
//import ItgHeroImageSwiper from './components/blocks/ItgHeroImageSwiper'
>>>>>>> 1c0f57ef3db213b3b4549380b570270ccc76a159
import ItgLogoWall from './components/blocks/ItgLogoWall'
import ItgContentCarousel from './components/blocks/ItgContentCarousel'
import ItgMatrix from './components/blocks/ItgMatrix'
import ItgRelatedLaunches12 from './components/blocks/ItgRelatedLaunches12'
import ItgAccordionCarousel from './components/blocks/ItgAccordionCarousel'
import ItgStakeholder from './components/blocks/ItgStakeholder'
import ItgFixHeader from './components/animations/ItgFixHeader'
import ItgMediaFilter from './components/blocks/ItgMediaFilter'
import ItgAnchorsButtonsBar from './components/blocks/ItgAnchorsButtonsBar'
import ItgFocusBox from './components/blocks/ItgFocusBox'
import ItgBalanceSheets from './components/blocks/ItgBalanceSheets'
import ItgNoticesCommunications from './components/blocks/ItgNoticesCommunications'
import ItgEventList from './components/blocks/ItgEventList'
import ItgOpenPreHeaderBottomSide from './components/blocks/ItgOpenPreHeaderBottomSide'
import ItgOpenMegaMenu from './components/blocks/ItgOpenMegaMenu'
import ItgFooter from './components/animations/ItgFooter'
import ItgNavTabs from './components/atoms/ItgNavTabs'